---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: upf-dpdk
  namespace: upf
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_dpdk
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "sriov",
    "name": "dpdk_vf",
    "spoofchk": "off",
    "trust": "on",
    "link_state": "enable"
}'

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: upf-netdev
  namespace: upf
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_netdevice
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "sriov",
    "name": "sriov_vf",
    "link_state": "enable"
}'

---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: upf-lb
  namespace: upf
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_lb
spec:
  config: '{
    "cniVersion": "0.3.1",
    "type": "sriov",
    "name": "dpdk_pf",
    "trust": "on",
    "link_state": "enable"
}'
